services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_billing_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: nest_billing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
